apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: docker.io/library/course_service:v2
        # change if your app listens elsewhere
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP