apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
      - name: orchestrator-service
        image: docker.io/library/orchestrator_service:final
        ports:
        - containerPort: 5004
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  selector:
    app: orchestrator-service
  ports:
  - protocol: TCP
    port: 5004
    targetPort: 5004
  type: ClusterIP